@startuml
[Watchdog]
package "Linux"{
[Safety signal source] .. [QT App] : periodically get Image   
[Safety signal source] --> [Safety App] : Message
[Safety App] ..>[Watchdog] : Pet
}
[Watchdog] --> [Backlight] : kill line
@enduml