' Functional perspective Cluster Demo application
@startuml
package "Instrument Cluster" {
[Watchdog]
package "Cluster Controller" {
[QT-Application]
[Safety-Signal-source]
[Safety-App]
}
}

[Safety-Signal-source] --> [Safety-App]

[Safety-App] --> [Watchdog] : pet

[Safety-App] --> [QT-Application] : Corruption trigger
@enduml


