@startuml
box "Linux"
participant "Safety signal source" order 10
participant "Safety App" order 20
end box
participant "Watchdog" order 30
participant "Backlight" order 40


activate "Safety signal source"
activate "Watchdog"
"Safety signal source" -> "Safety signal source": Determine Safety status
note left
FM: Spatial Interference 
    -> Status determination wrong
end note
"Safety signal source" -> "Safety App": Send cyclic Safety status Message
note left
FM Spatial Interference 
    -> Message corrupted
FM Temporal Interference 
    -> Message too early/late/missing
end note
deactivate "Safety signal source"
activate "Safety App"
"Safety App" -> "Safety App": Check E2E
note left
FM: Spatial Interference 
    -> E2E check false negative
end note
alt E2E check passes
"Safety App" -> "Safety App": Check Safety Signal
note left
FM: Spatial Interference 
    -> Safety signal check corrupted
end note
alt Safety signal OK
"Safety App" -> "Watchdog": Pet watchdog
note left
FM Spatial Interference 
    -> Message corrupted
FM Temporal Interference 
    -> Message too early/late/missing
end note
"Watchdog" -> "Watchdog": watchdog check
else Safety signal NOK
"Watchdog" -> "Watchdog": watchdog check
"Watchdog" -> "Backlight": kill Backlight
end
else E2E miss
"Watchdog" -> "Watchdog": watchdog check
"Watchdog" -> "Backlight": kill Backlight
end
@enduml